In [1]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score
import pandas as pd
import numpy as np
import random

In [2]:
commodity_dict = {
    "arhar": "static/Arhar.csv",
    "bajra": "static/Bajra.csv",
    "barley": "static/Barley.csv",
    "copra": "static/Copra.csv",
    "cotton": "static/Cotton.csv",
    "sesamum": "static/Sesamum.csv",
    "gram": "static/Gram.csv",
    "groundnut": "static/Groundnut.csv",
    "jowar": "static/Jowar.csv",
    "maize": "static/Maize.csv",
    "masoor": "static/Masoor.csv",
    "moong": "static/Moong.csv",
    "niger": "static/Niger.csv",
    "paddy": "static/Paddy.csv",
    "ragi": "static/Ragi.csv",
    "rape": "static/Rape.csv",
    "jute": "static/Jute.csv",
    "safflower": "static/Safflower.csv",
    "soyabean": "static/Soyabean.csv",
    "sugarcane": "static/Sugarcane.csv",
    "sunflower": "static/Sunflower.csv",
    "urad": "static/Urad.csv",
    "wheat": "static/Wheat.csv"
}

In [3]:

depth = random.randrange(7, 18)
regressor = DecisionTreeRegressor(max_depth=depth)

In [10]:
from pydoc import describe


r2_lst = []
for commodity in commodity_dict:

    df = pd.read_csv(commodity_dict[commodity])
    temp = df.describe()
    loc = "descriptions/" + commodity + ".csv"
    temp.to_csv(loc)
    X = df.iloc[:, :-1].values
    Y = df.iloc[:, 3].values
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    regressor.fit(X_train, y_train)

    y_pred = regressor.predict(X_test)

    r2 = r2_score(y_test, y_pred)
    r2_lst.append(r2)
    # print('r2 score for perfect model is', r2)

In [34]:
commodity_lst = []
for commodity in commodity_dict:
    commodity_lst.append(commodity)

In [33]:
r2_lst

[0.9297187351383593,
 0.8351992039165578,
 0.47171087866979855,
 0.6521738160479749,
 0.8643058104269351,
 0.7185645657634041,
 -2.797623089522926,
 0.06058150603258461,
 0.5164190641747894,
 0.35410530037866417,
 0.8639820833979345,
 0.9365894915270425,
 0.9680780380158984,
 0.9829762241083847,
 0.9424179642105516,
 0.08515231773487908,
 0.8653317672200918,
 0.7307119609885004,
 0.21271250411954912,
 0.9963320004080448,
 -0.32712172732049205,
 0.899282408660618,
 0.5424184455137653]

In [35]:
df_frame = pd.DataFrame({"commodity":commodity_lst,"R2-score":r2_lst})

  commodity  R2-score
0     arhar  0.929719
1     bajra  0.835199
2    barley  0.471711
3     copra  0.652174
4    cotton  0.864306

In [36]:
df_frame

    commodity  R2-score
0       arhar  0.929719
1       bajra  0.835199
2      barley  0.471711
3       copra  0.652174
4      cotton  0.864306
5     sesamum  0.718565
6        gram -2.797623
7   groundnut  0.060582
8       jowar  0.516419
9       maize  0.354105
10     masoor  0.863982
11      moong  0.936589
12      niger  0.968078
13      paddy  0.982976
14       ragi  0.942418
15       rape  0.085152
16       jute  0.865332
17  safflower  0.730712
18   soyabean  0.212713
19  sugarcane  0.996332
20  sunflower -0.327122
21       urad  0.899282
22      wheat  0.542418

In [38]:
df_frame.to_csv("r2_score_table.csv")